/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emailworkshop;

import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author fabio
 */
public class InterfaceGUI extends javax.swing.JFrame {
    CheckinDAO dao;
    String emailAutentica,senhaAutentica,emailRecebe;
    boolean enviaEmailParticipante;
    /**
     * Creates new form InterfaceGUI
     */
    public InterfaceGUI() {
        JLabel lblMessageServ = new JLabel("Nome do servidor Mysql:");
        JTextField txtServ = new JTextField();
        Object[] serv = {lblMessageServ, txtServ};        
        JOptionPane.showMessageDialog(null, serv);        
        String servidor = txtServ.getText();
        
        JLabel lblMessageBD = new JLabel("Nome do banco de dados:");
        JTextField txtBD = new JTextField();
        Object[] bd = {lblMessageBD, txtBD};
        JOptionPane.showMessageDialog(null, bd);
        String banco = txtBD.getText();

        JLabel lblMessageUser = new JLabel("Nome do Usuario:");
        JTextField txtUser = new JTextField();
        Object[] user = {lblMessageUser, txtUser};
        JOptionPane.showMessageDialog(null, user);
        String usuario = txtUser.getText();

        JLabel lblMessagePas = new JLabel("Senha ");
        JTextField txtPas = new JTextField();
        Object[] pas = {lblMessagePas, txtPas};
        JOptionPane.showMessageDialog(null, pas);
        String senha = txtPas.getText();

        dao = new CheckinDAO(servidor,banco, usuario, senha);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mailFrom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        senhaFrom = new javax.swing.JPasswordField();
        enviaParticipante = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        mailTo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnGerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(500, 300));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));

        jLabel1.setText("Meu Email:");

        mailFrom.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel2.setText("Minha Senha:");

        enviaParticipante.setText("Enviar e-mail para os participantes");
        enviaParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviaParticipanteActionPerformed(evt);
            }
        });

        jLabel4.setText("Email Receptor:");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel5.setText("Gerador de Certificados UFPR");

        btnGerar.setBackground(java.awt.Color.cyan);
        btnGerar.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnGerar.setText("GERAR");
        btnGerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGerarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mailFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(senhaFrom)
                            .addComponent(mailTo)))
                    .addComponent(enviaParticipante)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(btnGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mailFrom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mailTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(enviaParticipante)
                .addGap(118, 118, 118))
        );

        mailFrom.getAccessibleContext().setAccessibleName("mailFrom");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 300;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviaParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviaParticipanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviaParticipanteActionPerformed

    private void btnGerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerarMouseClicked
        System.out.println("emailworkshop.InterfaceGUI.btnGerarMouseClicked()");
        emailAutentica = mailFrom.getText();
        senhaAutentica = senhaFrom.getText();
        emailRecebe = mailTo.getText();
        enviaEmailParticipante = enviaParticipante.isEnabled();
        EmailWorkshop.exe((ArrayList<Checkin>) dao.getLista(), emailAutentica, senhaAutentica, emailRecebe, enviaEmailParticipante);
        JOptionPane.showConfirmDialog(null, "execução terminada!");
    }//GEN-LAST:event_btnGerarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JCheckBox enviaParticipante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mailFrom;
    private javax.swing.JTextField mailTo;
    private javax.swing.JPasswordField senhaFrom;
    // End of variables declaration//GEN-END:variables

    
}
